[project]
name = "diabetes-prediction"
version = "0.1.0"
description = "Create project's virtual environment"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
]
